/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function plus(input: number, input1: number): number
export declare class JsAlgo {
  constructor(name: string)
  hash(v: string): string
  getName(): string
}
export type JsMatrix = Matrix
export declare class Matrix {
  constructor(data: Array<Array<number>>)
  mult(other: Array<Array<number>>): Matrix
  multiply(other: Matrix): Matrix
  display(): string
  toString(): string
}
