/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function plus(input: number, input1: number): number
export declare class JsAlgo {
  constructor(name: string)
  hash(v: string): string
  getName(): string
}
